// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Image } from "./Image";

export interface GroupedImages {
  groups: Array<Array<Image>>;
  dirName: string;
}
